sudo: required

dist: xenial

language: python

python:
  - "3.6"

services:
  - docker

install:
  - pip install -r requirements.txt

before_script:
  - python tester.py
  - make docker-image

script:
  - echo "Test is successful!"

deploy:
  # deploy develop to the staging environment
  - provider: script
    script: bash run_server.sh staging
    on:
      branch: develop
  # deploy master to production
  - provider: script
    script: bash run_server.sh production
    on:
      branch: master

branches:
  only:
    - develop
    - master
