language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

deploy:
  - provider: script
    script: run_server.sh
    on:
      branch: develop
      condition: $RUN_DEPLOYMENT = "TRUE"
