sudo: required

language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

notification:
  email:
    recipient:
      - parsayousefi@aol.com
    on_success: always
    on_failure: always
