sudo: required

language: python

python:
  - "3.6"

services:
  - docker

install:
  - pip install -r requirements.txt

before_deploy:
  - python tester.py
  - make docker-image

deploy:
  - provider: script
    script: run_server.sh staging
    on:
      branch: develop
  
  - provider: script
    script: run_server.sh production
    on:
      branch: master

branches:
  only:
    - develop
    - master
